# =============================================================================
# CI Pipeline - Minimal für Solo Developer
# =============================================================================
# Philosophie:
# - Pre-push hook läuft lokal (TypeCheck + Unit Tests)
# - CI = nur Build-Check als Absicherung
# - Schnell & effizient: ~5 Minuten statt 30+
# =============================================================================

name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.vscode/**'
      - '.husky/**'
  pull_request:
    branches: [main]

# Cancel in-progress runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'

jobs:
  # =============================================================================
  # Minimal Check: Nur Build-Validierung
  # Tests laufen bereits lokal via pre-push hook
  # =============================================================================
  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Verify build output
        run: |
          if [ ! -d "dist" ] || [ -z "$(ls -A dist)" ]; then
            echo "❌ Build failed or dist directory is empty"
            exit 1
          fi
          echo "✅ Build successful"
